apiVersion: apps/v1
kind: Deployment
metadata:
name: my-deployment
labels:

app: my-deployment
spec:
replicas: 2
selector:
matchLabels:
app: my-deployment
template:
metadata:
labels:
app: my-deployment
spec:
containers:
- name: my-deployment
image: anusha2k1/website
ports:
- containerPort: 80
